
import { db } from './firebase';
import { collection, doc, setDoc, writeBatch, serverTimestamp, getDocs, deleteDoc } from 'firebase/firestore';

const chartOfAccounts = [
    // Assets
    { id: '1010', name: 'Cash and Bank', group: 'Current Assets', isDebitNormal: true },
    { id: '1020', name: 'Accounts Receivable', group: 'Current Assets', isDebitNormal: true },
    { id: '1030', name: 'Inventory - Perishables', group: 'Current Assets', isDebitNormal: true },
    { id: '1210', name: 'General Equipment', group: 'Fixed Assets', isDebitNormal: true },

    // Liabilities
    { id: '2010', name: 'Accounts Payable', group: 'Current Liabilities', isDebitNormal: false },
    { id: '2020', name: 'Member Reimbursements Payable', group: 'Current Liabilities', isDebitNormal: false },

    // Equity
    { id: '3010', name: 'Club Capital', group: 'Equity', isDebitNormal: false },
    { id: '3020', name: 'Retained Earnings', group: 'Equity', isDebitNormal: false },

    // Revenue
    { id: '4010', name: 'Sponsorship Income', group: 'Revenue', isDebitNormal: false },
    { id: '4020', name: 'Event Income', group: 'Revenue', isDebitNormal: false },

    // Expenses
    { id: '5010', name: 'Equipment Purchase (Deprecated)', group: 'Expenses', isDebitNormal: true }, // Kept for historical data
    { id: '5020', name: 'Event Expenses', group: 'Expenses', isDebitNormal: true },
    { id: '5030', name: 'Consumables & Parts', group: 'Expenses', isDebitNormal: true },
    { id: '5040', name: 'Bank Fees', group: 'Expenses', isDebitNormal: true },
    { id: '5050', name: 'Loss on Asset Retirement', group: 'Expenses', isDebitNormal: true },
];

const inventoryItems = [
    { id: 'inv-1', name: 'Metal Cupboard (1)', specifications: '5 Shelves', description: '', location: 'Back left corner of room', currentAllocation: 'Plane Team', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-2', name: 'Metal Cupboard (2)', specifications: '6 Shelves', description: '', location: 'Back left corner of room', currentAllocation: 'Drone Team', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-3', name: 'Small Metal Cupboard (3)', specifications: '3 Shelves', description: '', location: 'Back left corner of room', currentAllocation: 'Drone Team, Plane Team , Personal Use', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-4', name: 'Metal Cupboard', specifications: 'Belongs to the man Soni', description: 'It stays locked, dont ask', location: 'Back left corner of room', currentAllocation: 'Personal Use', itemType: 'Non Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-5', name: 'ESP32-S3-EYE', specifications: 'ESP32 with camera', description: 'for image recognition, speech processing', location: 'Thrust Stand Electronics box, Cupboard 1, Bottom Row', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-6', name: 'Load Cell (small)', specifications: 'small', description: 'Used for thrust stand', location: 'Thrust Stand Electronics box, Cupboard 1, Bottom Row', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-7', name: 'Load Cell (Big)', specifications: 'Big', description: 'Used for thrust stand', location: 'Thrust Stand Electronics box, Cupboard 1, Bottom Row', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-8', name: 'Depron Hexagonal Panels', specifications: 'Laser cut from depron', description: 'probably can be used for some plane...?', location: 'Cupboard 1, Row 3', currentAllocation: 'Unallocated', itemType: 'Raw Material', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-9', name: 'P32 Tail wing part', specifications: 'XPS foam airfoil', description: 'made for the p32', location: 'Cupboard 1, Row 3', currentAllocation: 'Plane Team', itemType: 'Fabrications', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-10', name: 'Waveshare SC15 Servo', specifications: '17kg large torque servo', description: 'insane wali hai', location: 'Box 1, Cupboard 1, Row 3', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-11', name: 'FC 03', specifications: 'Optical Speed sensor', description: 'used for sensing speed of motors, etc', location: 'Box 1, Cupboard 1, Row 3', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-12', name: 'Jhaadu', specifications: 'Please do use often', description: '', location: 'Below centre table', currentAllocation: 'Unallocated', itemType: 'Maintenance', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-13', name: 'Dustpan', specifications: '', description: '', location: 'Below Centre table', currentAllocation: 'Unallocated', itemType: 'Maintenance', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-14', name: 'SpeedyBee F405', specifications: 'Flight Controller stacked on PDB', description: '', location: 'SpeedyBee Box, Box 5, Row0, Cupboard1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-15', name: 'EMax multirotor motor', specifications: '1900 kv', description: '', location: 'Box2, Row 0, Cupboard1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-16', name: '0 drag Aurora Race-X', specifications: 'LED Strips', description: '', location: 'Box2, Row 0, Cupboard1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-17', name: 'FTDI board', specifications: 'Converts USB-B to another output', description: '', location: 'Box3, Row3, Cupboard 1', currentAllocation: 'Drone Team', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-18', name: 'Arduino Pro mini', specifications: '', description: '', location: 'Box3, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-19', name: 'ESP832', specifications: '', description: '', location: 'Box3, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-20', name: 'Voltage Converter', specifications: '', description: '', location: 'Box3, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-21', name: '5V Relay Module', specifications: '', description: '', location: 'Box 4, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-22', name: 'Single Relay board VO-1', specifications: '', description: '', location: 'Box 4, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-23', name: 'Logic level Converter', specifications: '', description: '', location: 'Box 4, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-24', name: 'QAPASS LCD Display', specifications: '', description: '', location: 'Box 4, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-25', name: 'QA LCD Display Mini', specifications: '', description: '', location: 'Box 4, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-26', name: 'DHT11', specifications: 'Temp, Humidity Sensor', description: '', location: 'Box 4, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-27', name: 'Doble Relay', specifications: '2 Relay Module', description: '', location: 'Box 4, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-28', name: 'XL4015', specifications: '5A DC-DC Step down Buck Converter module', description: '', location: 'Box 4, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-29', name: 'SpeedyBee TX 800', specifications: '', description: '', location: 'Box 5, Row0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-30', name: '3D printed Stuff', specifications: '', description: 'probaly useless, please see', location: '3D printed Boxes, Row 3, Cupboard 1', currentAllocation: 'Other (See description)', itemType: 'Fabrications', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-31', name: 'LM2596', specifications: 'dc-dc buck Converter', description: '', location: 'Box 6, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-32', name: 'RGB LED board 5050', specifications: '5V', description: '', location: 'Box 6, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-33', name: 'ST L7805CV', specifications: 'Voltage Regulators', description: '', location: 'Box 6, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-34', name: 'SMD LED CHIPS', specifications: '', description: '', location: 'Box 6, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-35', name: 'Micro Motor', specifications: '720 7mm Dia DC 3V-3.7V', description: 'for drones n quadcopters', location: 'Box 6, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-36', name: 'Blue LED modules', specifications: '12V 3mm', description: '', location: 'Box 6, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-37', name: 'Red LED modules', specifications: '12V, 3mm', description: '', location: 'Box 6, Row3, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-38', name: 'Ignition System', specifications: '', description: 'made by the Rishit the Kharbanda', location: 'IGN System Box, row 0, cupboard 1', currentAllocation: 'Plane Team, Drone Team', itemType: 'Maintenance', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-39', name: 'Airspeed Analog V1.1', specifications: 'Pitot tube airspeed sensor', description: '', location: 'Box 7, row 0, cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-40', name: 'Power Module V6.0', specifications: '', description: '', location: 'Box 7, row 0, cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-41', name: 'Brushleless motor', specifications: '1100 kv', description: 'has a drone arm attached to it', location: 'Row 0, cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-42', name: 'Packed Brushless Motor', specifications: 'Emax multicopter motor, 935 kv', description: 'has 2 props with it', location: 'Row 0, cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-43', name: 'Misc Boxes', specifications: 'Miscelleneous', description: '', location: 'Bottom row, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-44', name: 'Dji spark drone', specifications: '', description: 'Arm is broken, Dji box', location: 'Row 1, Cupboard 1', currentAllocation: 'Drone Team', itemType: 'Drone', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-45', name: 'Masks', specifications: 'Disposable', description: 'Face mask box', location: 'Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-46', name: 'ESC', specifications: '30Amps', description: '', location: 'Box 9, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-47', name: 'Motors (Ready toski 2300 kv)', specifications: 'Ready toski 2300 kv', description: '', location: 'Box 8, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-48', name: 'Motors (Ready toski 2212- 920 kv)', specifications: 'Ready toski 2212- 920 kv', description: '', location: 'Box 8, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-49', name: 'Fotek SSR- 25DA', specifications: 'DC - ACVoltage converter', description: '', location: 'Box 9, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-50', name: 'CADDX FPV Rattle 2', specifications: 'Rattle 2', description: '', location: 'Tray 1, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-51', name: 'Touch Sensor', specifications: '', description: '', location: 'Tray 1, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-52', name: 'Hw 504 Joystick module', specifications: 'Hw 139', description: '', location: 'Tray 1, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-53', name: 'Max 6675 K-type thermocup sensor module', specifications: 'Temperature measuring sensor', description: '', location: 'Tray 1, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-54', name: 'Taparia Screw drivers set', specifications: 'Orange Coloured', description: '', location: 'Row 0, cupboard 1', currentAllocation: 'Unallocated', itemType: 'Hardware Tools', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-55', name: 'DC-DC step down buck converter module', specifications: 'XY-3606 model', description: '', location: 'Tray 1, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-56', name: 'DoBoFo Edf', specifications: 'D2836, 3500KV-4s', description: '', location: 'Tray 1, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-57', name: 'Gopro Case', specifications: '', description: '', location: 'Tray 1, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Mechanical Parts', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-58', name: '2-axis brushless Gimbal', specifications: 'Gimbal', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-59', name: 'Quadcopter PDB', specifications: '', description: '', location: 'Tray 1, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-60', name: 'allen key', specifications: '4.5 cm, 1.5 cm length', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Hardware Tools', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-61', name: 'Antenna', specifications: 'Unknown', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-62', name: 'After Burner Prototype 1', specifications: 'Prototype', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Mechanical Parts', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-63', name: 'Male plug charger', specifications: 'Charger', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-64', name: 'Cable B type', specifications: 'B type cable', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-65', name: 'Speedybee Antenna', specifications: '5.8 GHz 2.8dBi Antenna', description: '1piece in a box of 2', location: 'Speedybee box, Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-66', name: 'coin cell', specifications: 'cr-2032, 3v', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-67', name: 'Eachine K-Loverleaves Mushroom Antenna', specifications: '5.8G 5dBi 6-Leaf Clover SMA/RP-SMA', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-68', name: 'Tactile push button switch', specifications: '', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-69', name: 'Box 10', specifications: 'The box of Boxes', description: 'it will box your boxes till you need the boxes from the box', location: 'Box 10, Bottom Row, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-70', name: 'MMCX', specifications: 'Micro miniature Coaxial', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-71', name: 'momentary push button', specifications: '', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-72', name: 'RF coaxial pigtail cable', specifications: 'MMCX to SMA adapter cable', description: '', location: 'Tray 2, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-73', name: 'Banana plugs to T-plug connector', specifications: '', description: '', location: 'Box 11, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-74', name: 'Gimbal Motor 5288', specifications: '', description: '', location: 'Box 11, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-75', name: 'Buzzer', specifications: '', description: '', location: 'Box 11, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-76', name: 'Dys 1120 kv Motor', specifications: '1120 kv, D2836-7', description: '', location: 'Box 11, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-77', name: 'Dji 2212/920 kv motor', specifications: '2212/920 kv', description: '', location: 'Box 11, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-78', name: 'Crocodile clips cable', specifications: '', description: '', location: 'Box 11, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-79', name: 'Espressif', specifications: 'Esp 32-S3-WROOM-1', description: '', location: 'Box 11, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-80', name: 'RS 2205', specifications: '2300KV', description: '', location: 'Box 11, Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-81', name: '6.5 cm dia drone propellers', specifications: '', description: '', location: '', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-82', name: 'X-Box motherboard', specifications: 'x-box 360 motherboard', description: 'how tf', location: 'Row 2, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-83', name: 'Eachine EV800D FPV Goggles', specifications: '5.8G', description: 'A 3d printed outline is also there with it', location: 'Box 12, Row 2, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-84', name: 'Rubber Bands', specifications: 'Multipe', description: '', location: 'Box 12, Row 2, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-85', name: 'Glare Guard for Eachine Goggles', specifications: '', description: '', location: 'Box 12, Row 2, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-86', name: 'Eachine FPV VR Goggles Box', specifications: '', description: '', location: 'Row 2, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-87', name: 'Iron mini DIY', specifications: '', description: '', location: 'Bottom row, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Hardware Tools', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-88', name: 'TBS Triumph Stub RP-SMA antenna', specifications: '', description: '', location: 'Tray 2,Row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-89', name: 'Jumper wires', specifications: 'Without jumpers pins', description: 'About 6 feet, kinda gay', location: 'Box 13, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-90', name: 'Carbonfibre pieces', specifications: '', description: '', location: 'Box 13, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Raw Material', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-91', name: 'O-life remote', specifications: '', description: '', location: 'Box 13, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-92', name: 'DC motor with a small prop', specifications: '', description: '', location: 'Box 13, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-93', name: '4-digit red 7-segment LED display', specifications: '5461AS 0.56-inch', description: '', location: 'Box 13, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-94', name: 'Ekectrobot 10 segment super bright red LED', specifications: '', description: '', location: 'Box 13, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-95', name: 'Single digit Led display', specifications: 'Sun056CC RY 1007', description: '', location: 'Box 13, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-96', name: 'LM393 Optical Photosensitive LDR light sensor module', specifications: '', description: '', location: 'Box 13, Row 0, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-97', name: 'Glue Gun sticks', specifications: 'Packets of 5', description: '', location: 'Glue Gun box(14),Row 2, cupboard 1', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 5, availableQuantity: 5, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-98', name: 'Pibox inspire Harddrive', specifications: 'Harddisk', description: '', location: 'row 1, Cupboard 1', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-99', name: 'Glue Gun', specifications: '60W,', description: 'new', location: 'Glue Gun box(14), Row 2, cupboard 1', currentAllocation: 'Unallocated', itemType: 'Hardware Tools', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-100', name: 'Black wire', specifications: '', description: 'black af', location: 'Bottom row, cupboard 1', currentAllocation: 'Unallocated', itemType: 'Raw Material', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-101', name: 'Chair plastic', specifications: '', description: 'Blue, supports approximately one whole achyut(not sure tho)', location: 'RC room', currentAllocation: 'Drone Team, Plane Team , Personal Use', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-102', name: 'Wooden Stool', specifications: '', description: '', location: 'RC room', currentAllocation: 'Drone Team, Plane Team , Personal Use', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-103', name: 'Wooden chair', specifications: '', description: 'location of the most important ppl in the room', location: 'RC room', currentAllocation: 'Drone Team, Plane Team , Personal Use', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-104', name: 'Black chair', specifications: 'backrest is broken', description: '', location: 'RC room', currentAllocation: 'Drone Team, Plane Team , Personal Use', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-105', name: 'Table', specifications: 'To be used while sitting', description: 'position of power and productivity', location: 'Rc room', currentAllocation: 'Drone Team, Plane Team , Personal Use', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-106', name: 'Work Table', specifications: '', description: 'initiation point of hopes and dreams', location: 'RC room', currentAllocation: 'Drone Team, Plane Team , Personal Use', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-107', name: 'Step Work Table', specifications: '', description: '', location: 'RC room', currentAllocation: 'Drone Team, Plane Team , Personal Use', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-108', name: 'Pin Board', specifications: '', description: '', location: 'Back of RC room', currentAllocation: 'Drone Team, Plane Team , Personal Use', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-109', name: 'Curtains', specifications: '', description: '', location: 'RC room windows', currentAllocation: 'Drone Team, Plane Team , Personal Use', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-110', name: 'Flight Bag', specifications: 'The bag of dreams', description: '', location: 'RC', currentAllocation: 'Drone Team, Plane Team , Personal Use', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-111', name: 'Black Rucksack small', specifications: '', description: '', location: 'Shelf 0, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-112', name: 'Radiolink AT 10 Transmitter', specifications: '2.4GHz', description: 'Orange and black', location: 'Shelf 0, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-113', name: 'FrSKY Transmitter (Taranis Q, X7)', specifications: 'Taranis Q, X7', description: 'orange, antenna is broken', location: 'Shelf 0, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-114', name: 'FrSKY Transmitter (Taranis Q, X7) ', specifications: 'Taranis Q, X7', description: 'White', location: 'Shelf 0, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-115', name: 'Flysky CT 6B', specifications: '2.4 GHz', description: 'Black with purple joysticks', location: 'Shelf 2, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-116', name: 'Flysky FS-I6', specifications: '', description: 'Black with purple joysticks', location: 'Shelf 1, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-117', name: 'Mini hdmi to usb A cable', specifications: '', description: '', location: 'Shelf 0, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-118', name: 'PETG Orange 3D printer filament', specifications: 'dia 1.75, print temp:220-250 deg C', description: '', location: 'Shelf 0, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-119', name: 'PLA+ 3D Filament', specifications: 'dia 1.75, print temp:190-220 deg C', description: '', location: 'Shelf 0, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-120', name: 'Aux to Aux cable', specifications: 'braided', description: '', location: 'Shelf 0, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-121', name: 'Joystick cover radiomaster', specifications: '', description: 'Blue colored, rubber', location: 'Shelf 1, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Mechanical Parts', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-122', name: 'Misc Box', specifications: 'Miscelleneous', description: '', location: 'Shelf 2, Cupboard 3', currentAllocation: 'Unallocated', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-123', name: '2024 SNAPS', specifications: 'Apogee 24', description: '', location: '', currentAllocation: 'Unallocated', itemType: 'Fixed Asset', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-124', name: 'White cloth', specifications: 'Testing cloth', description: '', location: '', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-125', name: 'Pixhawk 2.4.8', specifications: '', description: '', location: 'Yog panjarale', currentAllocation: 'Personal Use', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-126', name: 'DST (Double sided tape)', specifications: 'Double sided tape', description: 'New', location: 'Shelf 1, Box 15, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-127', name: 'Thinner Glue sticks', specifications: 'Gluegun', description: 'Packet', location: 'Glue Gun box(14),Row 2, cupboard 1', currentAllocation: 'Drone Team, Plane Team', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-128', name: 'rubber band bag (1)', specifications: '', description: 'Packet', location: 'Shelf 1, Box 15, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-129', name: 'rubber band bag (2)', specifications: '', description: 'Packet', location: 'Shelf 1, Tray 3, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-130', name: 'Zip ties', specifications: '', description: 'Packet', location: 'Shelf 1, Box 15, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-131', name: 'Green ribbon', specifications: '', description: '', location: 'Shelf 1, Tray 3, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Raw Material', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-132', name: 'Fevikwik', specifications: '', description: 'Instant glue', location: 'Shelf 1, Tray 3, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-133', name: 'Pencil cell', specifications: 'eveready', description: 'battery cell (the ones used in clocks)', location: 'Shelf 1, Tray 3, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-134', name: 'Reflective tape', specifications: 'white', description: '', location: 'Shelf 1, Box 15, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-135', name: 'L brackets', specifications: 'Grey', description: '', location: 'Shelf 1, Box 16, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Hardware Tools', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-136', name: 'Firewall', specifications: '10 white and 1 balck', description: '', location: 'Shelf 1, Box 16, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Mechanical Parts', totalQuantity: 11, availableQuantity: 11, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-137', name: 'Transparent tape', specifications: 'normal tape', description: 'Pack of 6', location: 'Shelf 1, Cupboard 15', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 6, availableQuantity: 6, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-138', name: 'Fevicol (200g)', specifications: '200 g', description: '', location: 'Shelf 1, Cupboard 15', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-139', name: 'Fevicol (25g)', specifications: '25g', description: '', location: 'Shelf 1, Cupboard 15', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-140', name: 'Fevicol (20g)', specifications: '20g', description: '', location: 'Shelf 1, Cupboard 15', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-141', name: '4 black tapes', specifications: 'non electric', description: 'but black', location: 'Shelf 1, Cupboard 15', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 4, availableQuantity: 4, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-142', name: 'Nerolac synthetic emamel', specifications: '', description: '', location: 'Shelf 1, Cupboard 15', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-143', name: 'Truwell cpvc solvent cement', specifications: 'solvent cement', description: '', location: 'Shelf 1, Cupboard 15', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-144', name: 'Aluminium foil roll', specifications: '', description: '', location: 'Shelf 2, Cupboard 15', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-145', name: 'Caminowa Fertilizer', specifications: 'NPK 13:00:45', description: '', location: 'Shelf 2, Cupboard 15', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-146', name: 'Potassium Nitrate', specifications: 'Extra pure', description: '', location: 'Shelf 2, Cupboard 15', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-147', name: 'Casette gas', specifications: '225 g butane gas', description: '', location: 'Shelf 2, Cupboard 15', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-148', name: '2 transparent tapes', specifications: 'normal tapes', description: '', location: 'Shelf 1, Tray 3, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 2, availableQuantity: 2, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-149', name: 'Steel pins', specifications: 'In a box', description: '', location: 'Steel pin box, Shelf 2, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Hardware Tools', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-150', name: 'Control Horns box', specifications: 'Control horns 3d printed ones', description: 'White and orange', location: 'Control horns box, Shelf 1, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Mechanical Parts', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-151', name: 'Cycle spokes', specifications: 'Mostly bent', description: '', location: 'Shelf 1, Cupboad 5', currentAllocation: 'Unallocated', itemType: 'Raw Material', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-152', name: 'Baking Powder', specifications: '', description: '', location: 'Shelf 2, Cupboard 5', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-153', name: 'B1 Battery', specifications: '3S, 2200 mah, Pro range, Battery health 11.5V', description: 'Battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-154', name: 'B2 Battery', specifications: '3S, 2200mah, Pro range, Battery health 8.8V', description: 'Battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-155', name: 'B3 Battery', specifications: '3S 2200mah, Pro range, Battery health 7.75V', description: 'Battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-156', name: 'B4 Battery', specifications: '2S, Black battery, Battery health 8.53 V', description: 'Battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-157', name: 'B5 Battery', specifications: '3S, 2200mah, Pro range, Battery health 12.4V', description: 'Battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-158', name: 'B6 Battery', specifications: '3S, 2200mah, Pro range, Battery health 11.9V', description: 'Battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-159', name: 'B7 Battery', specifications: '3S, 2200mah, Pro range, Battery health 8.63V, A bit inflated', description: 'A bit inflated battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-160', name: 'B8 Battery', specifications: '4S, 4500mah, Pro range, Battery health 16.2V', description: 'Battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-161', name: 'B9 Battery', specifications: '6S, 1380mah, Pro range, Battery health 24.2V', description: 'Battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-162', name: 'B10 Raptor Battery', specifications: '4S, 3300mah, Pro range, Battery health 16.4V', description: 'Raptor Battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-163', name: 'B11 Raptor Battery', specifications: '4S, 2500mah, Pro range, Battery health 16.5V', description: 'Raptor Battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-164', name: 'B12 Battery', specifications: '3S, 2200mah, ZOP power, Battery health 11.7V', description: 'Inflated black battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-165', name: 'B13 Battery', specifications: '2S, 2000mah, Black battery, Battery health 8.12', description: 'A bit inflated battery', location: 'Battery box', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-166', name: 'B14 Battery', specifications: '3S, 2200mah, Pro range, Battery health 12.1V', description: 'A bit inflated battery', location: 'Outside', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-167', name: 'B15 Battery', specifications: '3S, 5200mah, Pro range, Battery health 7.69V', description: 'A bit inflated battery', location: 'Outside', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-168', name: 'B16 Battery', specifications: '4S, 3300mah, Pro range, Battery health 13.3V', description: 'A bit inflated battery', location: 'Outside', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-169', name: 'FiberGlass Tape', specifications: '', description: '', location: '', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-170', name: 'WeAct Studio Demo motherboard', specifications: 'STM32H743VIT6-LCD', description: '', location: '', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-171', name: 'Noel Solder Wire', specifications: '', description: '', location: '', currentAllocation: 'Unallocated', itemType: 'Perishables', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: true },
    { id: 'inv-172', name: 'female to female jumper wires', specifications: '', description: '', location: '', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-173', name: 'header pins', specifications: '', description: '', location: '', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
    { id: 'inv-174', name: 'Breakout board PCB for UWB modules', specifications: '', description: '', location: '', currentAllocation: 'Unallocated', itemType: 'Electronics', totalQuantity: 1, availableQuantity: 1, checkedOutQuantity: 0, isPerishable: false },
].map((item, index) => ({
    id: `inv-${index + 1}`,
    ...item,
    totalQuantity: item.totalQuantity || 1,
    availableQuantity: item.availableQuantity || item.totalQuantity || 1,
    checkedOutQuantity: item.checkedOutQuantity || 0,
    isPerishable: item.itemType === 'Perishables'
}));

const reimbursements = [];

const seedCollection = async (collectionName: string, data: any[]) => {
    if (collectionName === 'reimbursements') {
        console.log('Clearing reimbursements collection...');
        const querySnapshot = await getDocs(collection(db, 'reimbursements'));
        const deleteBatch = writeBatch(db);
        querySnapshot.forEach(doc => {
            deleteBatch.delete(doc.ref);
        });
        await deleteBatch.commit();
        console.log('Reimbursements collection cleared.');
    }

    if (data.length === 0) {
    console.log(`Skipping seeding for ${collectionName} as no data is provided.`);
    return;
  }
  console.log(`Seeding ${collectionName}...`);
  const batch = writeBatch(db);
  data.forEach((item) => {
    const docRef = doc(db, collectionName, item.id);
    const dataWithTimestamp = { ...item, createdAt: serverTimestamp() };
    batch.set(docRef, dataWithTimestamp);
  });
  await batch.commit();
  console.log(`${collectionName} seeded successfully.`);
};

const seedPermissions = async () => {
    console.log('Seeding permissions...');
    const permissionsByRole = {
        admin: { canApproveInventory: true, canApproveNewItemRequest: true, canApproveProjects: true, canCloseProjects: true, canCreateBuckets: true, canCreateProjects: true, canExportFinanceLogs: true, canHoldKey: true, canManageInventoryStock: true, canManageUsers: true, canMarkNewItemOrdered: true, canRequestInventory: true, canRequestNewItem: true, canSubmitReimbursements: true, canViewAllProjects: true, canViewAllUsers: true, canViewDashboardMetrics: true, canViewFinanceSummary: true, canViewInventoryLogs: true },
        coordinator: { canApproveInventory: true, canApproveNewItemRequest: true, canApproveProjects: true, canCloseProjects: true, canCreateBuckets: true, canCreateProjects: true, canExportFinanceLogs: false, canHoldKey: true, canManageInventoryStock: false, canManageUsers: true, canMarkNewItemOrdered: true, canRequestInventory: true, canRequestNewItem: true, canSubmitReimbursements: true, canViewAllProjects: true, canViewAllUsers: true, canViewDashboardMetrics: true, canViewFinanceSummary: true, canViewInventoryLogs: true },
        drone_lead: { canApproveInventory: false, canApproveNewItemRequest: false, canApproveProjects: true, canCloseProjects: true, canCreateBuckets: true, canCreateProjects: true, canExportFinanceLogs: false, canHoldKey: true, canManageInventoryStock: false, canManageUsers: false, canMarkNewItemOrdered: false, canRequestInventory: true, canRequestNewItem: true, canSubmitReimbursements: true, canViewAllProjects: false, canViewAllUsers: false, canViewDashboardMetrics: true, canViewFinanceSummary: false, canViewInventoryLogs: false },
        inventory_manager: { canApproveInventory: true, canApproveNewItemRequest: true, canApproveProjects: false, canCloseProjects: false, canCreateBuckets: true, canCreateProjects: true, canExportFinanceLogs: false, canHoldKey: true, canManageInventoryStock: true, canManageUsers: false, canMarkNewItemOrdered: true, canRequestInventory: true, canRequestNewItem: true, canSubmitReimbursements: true, canViewAllProjects: true, canViewAllUsers: false, canViewDashboardMetrics: true, canViewFinanceSummary: false, canViewInventoryLogs: true },
        member: { canApproveInventory: false, canApproveNewItemRequest: false, canApproveProjects: false, canCloseProjects: false, canCreateBuckets: true, canCreateProjects: true, canExportFinanceLogs: false, canHoldKey: false, canManageInventoryStock: false, canManageUsers: false, canMarkNewItemOrdered: false, canRequestInventory: true, canRequestNewItem: true, canSubmitReimbursements: true, canViewAllProjects: false, canViewAllUsers: false, canViewDashboardMetrics: false, canViewFinanceSummary: false, canViewInventoryLogs: false },
        plane_lead: { canApproveInventory: false, canApproveNewItemRequest: false, canApproveProjects: true, canCloseProjects: true, canCreateBuckets: true, canCreateProjects: true, canExportFinanceLogs: false, canHoldKey: true, canManageInventoryStock: false, canManageUsers: false, canMarkNewItemOrdered: false, canRequestInventory: true, canRequestNewItem: true, canSubmitReimbursements: true, canViewAllProjects: false, canViewAllUsers: false, canViewDashboardMetrics: true, canViewFinanceSummary: false, canViewInventoryLogs: false },
        probationary: { canApproveInventory: false, canApproveNewItemRequest: false, canApproveProjects: false, canCloseProjects: false, canCreateBuckets: false, canCreateProjects: false, canExportFinanceLogs: false, canHoldKey: false, canManageInventoryStock: false, canManageUsers: false, canMarkNewItemOrdered: false, canRequestInventory: true, canRequestNewItem: true, canSubmitReimbursements: true, canViewAllProjects: false, canViewAllUsers: false, canViewDashboardMetrics: false, canViewFinanceSummary: false, canViewInventoryLogs: false },
        treasurer: { canApproveInventory: true, canApproveNewItemRequest: true, canApproveReimbursements: true, canApproveProjects: false, canCloseProjects: false, canCreateBuckets: true, canCreateProjects: true, canExportFinanceLogs: true, canHoldKey: true, canManageInventoryStock: true, canManageUsers: false, canMarkNewItemOrdered: true, canRequestInventory: true, canRequestNewItem: true, canSubmitReimbursements: true, canViewAllProjects: true, canViewAllUsers: true, canViewDashboardMetrics: true, canViewFinanceSummary: true, canViewInventoryLogs: true }
    };
    const promises = Object.entries(permissionsByRole).map(([role, permissions]) => {
        const docRef = doc(db, 'permissions', role);
        return setDoc(docRef, permissions);
    });
    await Promise.all(promises);
    console.log('Permissions seeded successfully.');
};


const seedDatabase = async () => {
  try {
    await seedCollection('chart_of_accounts', chartOfAccounts);
    await seedCollection('inventory_items', inventoryItems);
    await seedCollection('reimbursements', reimbursements);
    await seedPermissions();
    
    console.log('\n✅ Database seeded with new finance schema!');
  } catch (error) {
    console.error('Error seeding database:', error);
  }
};

seedDatabase().then(() => {
    if (typeof process !== 'undefined') {
        process.exit(0);
    }
});
